import fs from "node:fs/promises";
import path from "node:path";
import type { ProjectBlueprint } from "../contracts/index.js";
import { pathExists, writeJson } from "../utils/fs.js";

export async function writeWorkspaceFiles(root: string, blueprint: ProjectBlueprint): Promise<void> {
  if (blueprint.workspace !== "monorepo") return;

  const jsApps = blueprint.apps.filter((app) =>
    ["web", "mobile", "browser-extension"].includes(app.target),
  );
  const scripts: Record<string, string> = {};
  for (const app of jsApps) {
    scripts[`dev:${app.id}`] = `pnpm --dir ${app.path} ${app.target === "mobile" ? "start" : "dev"}`;
  }
  const api = blueprint.apps.find((app) => app.target === "api");
  if (api) {
    scripts["dev:api"] = `uv --directory ${api.path} run python manage.py runserver`;
    scripts["migrate:api"] = `uv --directory ${api.path} run python manage.py migrate`;
  }

  await writeJson(path.join(root, "package.json"), {
    name: path.basename(root),
    private: true,
    scripts,
  });

  const workspaceLines = ["packages:"];
  for (const app of jsApps) workspaceLines.push(`  - '${app.path}'`);
  workspaceLines.push("  - 'packages/*'");
  await fs.writeFile(path.join(root, "pnpm-workspace.yaml"), `${workspaceLines.join("\n")}\n`, "utf8");

  const ignorePath = path.join(root, ".gitignore");
  const existing = (await pathExists(ignorePath)) ? await fs.readFile(ignorePath, "utf8") : "";
  const ignoreLines = new Set(
    `${existing}\nnode_modules/\n.env\n.env.*\n!.env.example\n.venv/\n__pycache__/\n.pytest_cache/\n.ruff_cache/\n.expo/\ndist/\nbuild/\n.DS_Store\n`
      .split("\n")
      .map((line) => line.trimEnd()),
  );
  await fs.writeFile(ignorePath, `${[...ignoreLines].join("\n").trim()}\n`, "utf8");

  const appLines = blueprint.apps
    .map((app) => `- \`${app.path}\` — ${app.target} (${app.foundationId})`)
    .join("\n");
  await fs.writeFile(
    path.join(root, "README.md"),
    `# ${path.basename(root)}\n\nGenerated by Fonij CLI.\n\n## Applications\n\n${appLines}\n\n## Development\n\nRun the root scripts from \`package.json\`, or work inside an individual app directory.\n\n## Fonij\n\nRun \`fonij inspect\` to inspect the project architecture and \`fonij add <target>\` to evolve it.\n`,
    "utf8",
  );
}
